version: '3.7'
services:
  backend:
    image: service-backend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quvault-backend
    platform: linux/amd64
    env_file:
      - .env
    ports:
      - '3001:3001'
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=quvault
      - POSTGRES_USER=quvault
      - POSTGRES_PASSWORD=quvault
    ports:
      - '5433:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U quvault -d quvault']
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  redis:
    image: redis:6
    ports:
      - '6381:6379'
  # worker:
  #   image: service-worker
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.worker
  #   container_name: quvault-worker
  #   platform: linux/amd64
  #   env_file:
  #     - .env
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '1025:1025'
      - '8025:8025'
    restart: on-failure
